import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from src.db.base import Base


class Competitor(Base):
    __tablename__ = "competitors"

    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False, unique=True)
    meta_page_id = Column(String(64))
    meta_search_terms = Column(String(255))
    tiktok_handle = Column(String(128))
    country = Column(String(8), default="US")
    is_own_brand = Column(Boolean, default=False)
    notes = Column(String(255))
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


class MetaAd(Base):
    """One ad captured from Meta's public Ad Library API (`/ads_archive`).

    Note: spend/impressions are only populated by Meta for POLITICAL_AND_ISSUE_ADS
    in a handful of countries - for ordinary commercial ads those columns stay
    empty by design. See src/collectors/meta_ads_library.py.
    """

    __tablename__ = "meta_ads"

    id = Column(String(64), primary_key=True)
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    page_id = Column(String(64))
    page_name = Column(String(255))
    ad_creative_body = Column(Text)
    ad_creative_link_title = Column(Text)
    ad_creative_link_caption = Column(Text)
    ad_snapshot_url = Column(Text)
    publisher_platforms = Column(String(255))
    ad_delivery_start_time = Column(DateTime)
    ad_delivery_stop_time = Column(DateTime, nullable=True)
    languages = Column(String(255))
    spend_lower = Column(Float, nullable=True)
    spend_upper = Column(Float, nullable=True)
    impressions_lower = Column(Float, nullable=True)
    impressions_upper = Column(Float, nullable=True)
    content_hash = Column(String(64), index=True)
    first_seen_at = Column(DateTime, default=datetime.datetime.utcnow)
    last_seen_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor")


class TikTokAd(Base):
    """One ad/video captured from TikTok Creative Center's public Top Ads data.

    Best-effort / unofficial - see src/collectors/tiktok_creative_center.py.
    """

    __tablename__ = "tiktok_ads"

    id = Column(String(64), primary_key=True)
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    brand_name = Column(String(255))
    video_url = Column(Text)
    thumbnail_url = Column(Text)
    caption = Column(Text)
    likes = Column(Integer, nullable=True)
    comments = Column(Integer, nullable=True)
    shares = Column(Integer, nullable=True)
    metrics_json = Column(Text, nullable=True)
    first_seen_at = Column(DateTime, default=datetime.datetime.utcnow)
    last_seen_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor")


class OwnAdInsight(Base):
    """Daily performance row for your own connected Meta Ads account, pulled
    from the Marketing API's /insights endpoint."""

    __tablename__ = "own_ad_insights"
    __table_args__ = (UniqueConstraint("ad_id", "date", name="uq_ad_date"),)

    id = Column(Integer, primary_key=True, autoincrement=True)
    ad_account_id = Column(String(64))
    campaign_id = Column(String(64))
    campaign_name = Column(String(255))
    adset_id = Column(String(64))
    adset_name = Column(String(255))
    ad_id = Column(String(64))
    ad_name = Column(String(255))
    date = Column(DateTime)
    spend = Column(Float)
    impressions = Column(Float)
    clicks = Column(Float)
    ctr = Column(Float)
    cpc = Column(Float)
    cpm = Column(Float)
    reach = Column(Float)
    frequency = Column(Float)
    purchases = Column(Float, nullable=True)
    purchase_value = Column(Float, nullable=True)
    roas = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


class Prediction(Base):
    """Forecast rows generated by src/analysis/forecasting.py."""

    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    metric_name = Column(String(64))
    entity_type = Column(String(32))
    entity_id = Column(String(64))
    forecast_date = Column(DateTime)
    predicted_value = Column(Float)
    lower_bound = Column(Float, nullable=True)
    upper_bound = Column(Float, nullable=True)
    model_name = Column(String(64))
    generated_at = Column(DateTime, default=datetime.datetime.utcnow)


class WinningCreativeScore(Base):
    """Computed 'is this creative winning' proxy score, since Meta hides real
    spend/impressions for ordinary commercial competitor ads."""

    __tablename__ = "winning_creative_scores"

    id = Column(Integer, primary_key=True, autoincrement=True)
    source = Column(String(32))  # meta_competitor | tiktok_competitor
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=True)
    ad_ref_id = Column(String(64))
    days_running = Column(Float, nullable=True)
    variant_count = Column(Integer, default=1)
    score = Column(Float)
    rationale = Column(Text)
    computed_at = Column(DateTime, default=datetime.datetime.utcnow)
